### ISSUE TITLE
[fix] 엔티티 수정

### ISSUE THREAD

**Issue by yxinot** [PICK-PLE/PICKPLE-server#14]
## 📌  Feature Issue

- 엔티티 수정 사항을 반영합니다.
## 📝  To-do

- [x] applicant 폴더 네이밍 submitter로 수정
- [x] moimapplication 폴더 네이밍 moimsubmission으로 수정
- [x] Moim 및 MoimSubmittion 내부 필드 수정
