### ISSUE TITLE
[feat] 베테랑 스티커를 위한 response 추가 및 수정

### ISSUE THREAD

**Issue by bo-ram-bo-ram** [PICK-PLE/PICKPLE-server#222]
## 📝  To-do

- [ ] 모임에 해당하는 호스트 정보조회 -  count삭제 베테랑 추가
https://www.notion.so/API-ver2-04cb7fe6ff094412a6efc345b054af4b?pvs=4
- [ ] 호스트 정보 조회 - 베테랑 추가
https://www.notion.so/API-ver2-8b13bd07153b4a89b0f80b6dd91dc427?pvs=4
- [ ] 호스트 소개 조회 - count삭제 베테랑 추가
https://www.notion.so/API-d87748c2f4ab45bb8a42326eb4121fe0?pvs=4
