### ISSUE TITLE
[feat] 호스트 정보 조회 API 구현

### ISSUE THREAD

**Issue by bo-ram-bo-ram** [PICK-PLE/PICKPLE-server#29]
## 📌  Feature Issue

호스트 정보 조회 API를 구현합니다.

## 📝  To-do

- [ ] @hostId custom 어노테이션 구현
- [ ] 컨트롤러 구현
- [ ] repository 및 service 구현
- [ ] 호스트로 승인되기 전이면 hostId null로 내려지는지 확인
