### ISSUE TITLE
[fix] 회원가입 관련 수정

### ISSUE THREAD

**Issue by bo-ram-bo-ram** [PICK-PLE/PICKPLE-server#37]
## 📌  Feature Issue

카카오 소셜 로그인 시 각종 수정 사항을 반영합니다

## 📝  To-do

- [ ] guestId / hostId 반환
- [ ] 카카오 소셜 로그인 시 guest 정보도 함께 생성되도록 구현
    - [x] nickname 중복 방지를 위한 실명+id값으로 설정
