### ISSUE TITLE
[setting] sentry 연동

### ISSUE THREAD

**Issue by yxinot** [PICK-PLE/PICKPLE-server#5]
## 📌  Feature Issue
에러 모니터링을 위한 sentry 연동을 진행합니다.

## 📝  To-do

- [x] sentry 프로젝트 생성
- [x] spring boot 프로젝트에 sentry 연동
- [x] 에러 로그 올라오는지 확인
