### ISSUE TITLE
호스트와 모임상태에 해당하는 모임 조회 api 구현

### ISSUE THREAD

**Issue by bo-ram-bo-ram** [PICK-PLE/PICKPLE-server#67]
## 📌  Feature Issue

호스트에 해당하는 모임 조회 api를 구현합니다.

## 📝  To-do

- [x] controller구현
- [x] repository / service 구현
- [x] 예외처리
   - [x] 진행중인 모임이 없는 경우
   - [x] 완료한 모임이 없는 경우
